parameters:
  twig.path: "%tempalte_dir%/App/views"
  twig.options:
    debug:            "%WP_DEBUG%"
    charset:          "utf-8"
    cache:            null #"%tempalte_dir%/var/twig/views"
    auto_reload:      "%WP_DEBUG%"
    strict_variables: true
    autoescape:       true
    optimizations:    -1

services:
  twig.loader:
    class: "Twig_Loader_Filesystem"
    arguments: ["%twig.path%"]
  twig.post:
    class: "App\\Twig\\Post"
  twig.page:
    class: "App\\Twig\\Page"
  twig.fields:
    class: "App\\Twig\\Page"
  twig.attachment:
    class: "App\\Twig\\Attachment"
  twig.bookmark:
    class: "App\\Twig\\Bookmark"
  twig.terms:
    class: "App\\Twig\\Terms"
  twig.other:
    class: "App\\Twig\\Other"
  twig.environment:
    class: "Twig_Environment"
    arguments: ["@twig.loader", "%twig.options%"]
    calls:
      - [addExtension, ["@twig.post"]]
      - [addExtension, ["@twig.page"]]
      - [addExtension, ["@twig.attachment"]]
      - [addExtension, ["@twig.bookmark"]]
      - [addExtension, ["@twig.terms"]]